CREATE TYPE INE_PROV_NAME_ENUM AS ENUM (
    'UNDEFINED', -- so that ENUM code is 0 for UNDEFINED. Thanks to that
    /* The provinces below are listed in such order, so that ENUM codes for them will match with the official INE codes, e.g. Alicante/Alacant will match with internal ENUM code 3, and INE code for it is "03" */
    'Araba/Álava',
    'Albacete',
    'Alicante/Alacant',
    'Almería',
    'Ávila',
    'Badajoz',
    'Balears, Illes',
    'Barcelona',
    'Burgos',
    'Cáceres',
    'Cádiz',
    'Castellón/Castelló',
    'Ciudad Real',
    'Córdoba',
    'Coruña, A',
    'Cuenca',
    'Girona',
    'Granada',
    'Guadalajara',
    'Gipuzkoa',
    'Huelva',
    'Huesca',
    'Jaén',
    'León',
    'Lleida',
    'Rioja, La',
    'Lugo',
    'Madrid',
    'Málaga',
    'Murcia',
    'Navarra',
    'Ourense',
    'Asturias',
    'Palencia',
    'Palmas, Las',
    'Pontevedra',
    'Salamanca',
    'Santa Cruz de Tenerife',
    'Cantabria',
    'Segovia',
    'Sevilla',
    'Soria',
    'Tarragona',
    'Teruel',
    'Toledo',
    'Valencia/València',
    'Valladolid',
    'Bizkaia',
    'Zamora',
    'Zaragoza',
    'Ceuta',
    'Melilla'
);
